package AUDIT_RuleSet
expander audit.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.auditmanagement.re.AuditHelper;

# OBJECT        client_objid        LONG       Client ID                                                                                                                                                                                                      
# OBJECT        client_sign         CLIENTSIGN Client                                                                                                                                                                                                         
# OBJECT        create_date         DATE       Creation date                                                                                                                                                                                                  
# OBJECT        creator_user_id     LONG       User ID (creator)                                                                                                                                                                                              
# OBJECT        delete_date         DATE       Deletion date                                                                                                                                                                                                  
# OBJECT        guid                STRING     GUID                                                                                                                                                                                                           
# OBJECT        obj_id              LONG       ID                                                                                                                                                                                                             
# OBJECT        obj_type            OBJECTTYPE Object type                                                                                                                                                                                                    
# OBJECT        root_guid           STRING     Root GUID                                                                                                                                                                                                      
# OBJECT        versions            LONG       Number of versions                                                                                                                                                                                             
# VERSION       aris_change_date    DATE       ARIS change date                                                                                                                                                                                               
# VERSION       change_date         DATE       Change date                                                                                                                                                                                                    
# VERSION       change_type         ENUM       Change type                     changetype (created=0,unchanged=1,changed=2,deleted=3,xmlcreated=4,xmlchanged=5,xmldeleted=6)                                                                                  
# VERSION       change_user_id      LONG       User ID (editor)                                                                                                                                                                                               
# VERSION       deactivated         BOOLEAN    Deactivated                                                                                                                                                                                                    
# VERSION       id                  LONG       ID                                                                                                                                                                                                             
# VERSION       substitute_user_id  LONG       User ID (substitute)                                                                                                                                                                                           
# VERSION       version_active      BOOLEAN    Current version                                                                                                                                                                                                
# VERSION       version_number      LONG       Version number                                                                                                                                                                                                 
# TRANSACTIONAL execution_date      DATE       Audit date                                                                                                                                                                                                     
# TRANSACTIONAL owner               LIST       Performed by                    to 1 USER (LT=5180)                                                                                                                                                            
# TRANSACTIONAL owner_group         LIST       Audit owner group               to 1 USERGROUP (LT=5160)                                                                                                                                                       
# TRANSACTIONAL owner_status        ENUM       Status                          auditstatus (all=-1,open=-2,closed=-3,incomplete=-5,complete=-6,in_preparation=1,in_execution=-4,released=2,in_progress=3,conform=4,notconform=5,notauditable=6,notcompleted=7)
# TRANSACTIONAL owner_substitute    LIST       Substitute                      to 1 USER (LT=5190)                                                                                                                                                            
# TRANSACTIONAL review_date         DATE       Review date                                                                                                                                                                                                    
# TRANSACTIONAL reviewer            LIST       Audit reviewer                  to 1 USER (LT=5210)                                                                                                                                                            
# TRANSACTIONAL reviewer_group      LIST       Audit reviewer group            to 1 USERGROUP (LT=5200)                                                                                                                                                       
# TRANSACTIONAL reviewer_status     ENUM       Reviewer status                 audit_reviewer_status (all=-1,completed=-2,to_be_reviewed=-3,unspecified=0,accepted=1,rejected=2)                                                                              
# TRANSACTIONAL reviewer_substitute LIST       Reviewer (substitute)           to 1 USER (LT=5240)                                                                                                                                                            
# MONITORABLE   controlenddate      DATE       End date of control                                                                                                                                                                                            
# MONITORABLE   controlstartdate    DATE       Start date of control                                                                                                                                                                                          
# MONITORABLE   plannedenddate      DATE       End date of audit preparation                                                                                                                                                                                  
# MONITORABLE   plannedstartdate    DATE       Start date of audit preparation                                                                                                                                                                                
# AUDIT         actualenddate       DATE       End date of audit (actual)                                                                                                                                                                                     
# AUDIT         actualstartdate     DATE       Start date of audit (actual)                                                                                                                                                                                   
# AUDIT         audit_client        TEXT       Audit client                                                                                                                                                                                                   
# AUDIT         auditconclusion     TEXT       Result                                                                                                                                                                                                         
# AUDIT         auditenddate        DATE       End date of audit                                                                                                                                                                                              
# AUDIT         auditor_group       LIST       Audit auditor group             to 1 USERGROUP (LT=5220)                                                                                                                                                       
# AUDIT         auditstartdate      DATE       Start date of audit                                                                                                                                                                                            
# AUDIT         audittemplate       LIST       Audit template                  to 1 AUDITTEMPLATE (LT=5230)                                                                                                                                                   
# AUDIT         audittype           ENUM       Type                            audittype (all=-1,please_select=0,sox=1,iso=2,cobit=3,others=4)                                                                                                                
# AUDIT         audittype_text      TEXT       Type description                                                                                                                                                                                               
# AUDIT         conclusiondocuments LIST       Result documents                to * DOCUMENTs (LT=5170)                                                                                                                                                       
# AUDIT         description         TEXT       Description                                                                                                                                                                                                    
# AUDIT         documents           LIST       Documents                       to * DOCUMENTs (LT=5150)                                                                                                                                                       
# AUDIT         duestatus           ENUM       Due status                      duestatus (all=-1,on_time=1,overdue=2)                                                                                                                                         
# AUDIT         followup            LIST       Follow-up                       to * AUDITs (LT=5120)                                                                                                                                                          
# AUDIT         name                STRING     Name                                                                                                                                                                                                           
# AUDIT         notconformreason    ENUM       Reason                          notconformreason (all=-1,please_select=0,major=1,minor=2)                                                                                                                      
# AUDIT         objectives          TEXT       Audit objectives                                                                                                                                                                                               
# AUDIT         predecessor         LIST       Predecessor                     to 1 AUDIT (LT=5110)                                                                                                                                                           
# AUDIT         reviewer_documents  LIST       Documents (reviewer)            to * DOCUMENTs (LT=5360)                                                                                                                                                       
# AUDIT         reviewer_remark     TEXT       Remark (reviewer)                                                                                                                                                                                              
# AUDIT         scope               LIST       Audit scope                     to 1 OBJECT (LT=5130)                                                                                                                                                          
# AUDIT         steps               LIST       Audit steps                     to * AUDITSTEPs (LT=5140)                                                                                                                                                      

# DO NOT CHANGE THE LINES ABOVE - all of them will be updated automatically by tool com.idsscheer.webapps.arcm.bl.re.RETemplater

################################################
### All workflow states - before state rules ###

rule "set audit attributes invisible [I,V]"

    salience 10000
    no-loop true

    when

    then
        set "audittype_text" invisible
        set "notconformreason" invisible

end

##############################################################
### Workflow state "preparationPhase" and "executionPhase" ###
    
#rule "define audittype mandatory [I,V]"

 #   salience 2500
#    no-loop true
                       
#    when
#        user has at object role "auditowner"
#        is in workflow state "preparationPhase"
#        value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "released"

#	then               	
#        set "audittype" mandatory

#end

rule "define manager editable & mandatory [I,V]"

    salience 2400
    no-loop true

    when
    	user has at object role "auditmanager"
    	( is in workflow state "preparationPhase" OR
    	is in workflow state "executionPhase" )

    then
        set "owner_group" editable
        set "reviewer_group" editable
        set "auditor_group" editable

        set "owner_group" mandatory
        set "reviewer_group" mandatory

end

rule "define owner editable & mandatory [I,V]"

    salience 2300
    no-loop true

    when
    	user has at object role "auditowner"
    	( is in workflow state "preparationPhase" OR
    	is in workflow state "executionPhase" )

    then
        set "name" editable
        set "description" editable
        set "objectives" editable
        set "scope" editable
#        set "audittype" editable
        set "audit_client" editable
        set "documents" editable
        set "predecessor" editable
        set "auditenddate" editable
        set "auditstartdate" editable
        set "controlenddate" editable
        set "controlstartdate" editable
        set "owner_status" editable
        set "auditconclusion" editable
        set "conclusiondocuments" editable
        set "steps" editable
        set "reviewer_group" editable
        set "auditor_group" editable
#        set "risk" editable
#        set "methodology" editable
#        set "regulation" editable
#        set "process" editable

        set "name" mandatory
        set "auditstartdate" mandatory
		set "auditenddate" mandatory
#		set "audit_client" mandatory
        set "reviewer_group" mandatory

end

rule "define audittype_text mandatory [I,V]"

    salience 2200
    no-loop true

    when
    	user has at object role "auditowner"
    	( is in workflow state "preparationPhase" OR
    	is in workflow state "executionPhase" )
    	value comparison fulfilled: ":transient:" attr_value "audittype" "CONTAINS" value "others"

    then
        set "audittype_text" visible
        set "audittype_text" editable
        set "audittype_text" mandatory

end

rule "define notconformreason mandatory [I,V]"

    salience 2100
    no-loop true

    when
    	user has at object role "auditowner"
    	is in workflow state "executionPhase"
        value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "notconform"

	then
        set "notconformreason" visible
        set "notconformreason" editable
        set "notconformreason" mandatory

end

rule "define auditconclusion mandatory [I,V]"

    salience 2000
    no-loop true

    when
        user has at object role "auditowner"
        is in workflow state "executionPhase"
        ( value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "notconform" OR
          value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "notauditable" OR
          value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "notcompleted" )

	then
		set "auditconclusion" mandatory

end

###############################
### Workflow state "closed" ###
rule "define reviewer editable [I,V]"

    salience 1100
    no-loop true

    when
    	user has at object role "auditreviewer"
    	is in workflow state "closed"

    then
        set "reviewer_status" editable
        set "reviewer_remark" editable
        set "reviewer_documents" editable

end

rule "define reviewer remark mandatory [I,V]"

    salience 1000
    no-loop true

    when
    	user has at object role "auditreviewer"
    	is in workflow state "closed"
    	value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "rejected"

    then
        set "reviewer_remark" mandatory

end

###############################################
### All workflow states - after state rules ###
rule "step period invalid_[V]"

	salience 190
	no-loop true

	when
		"steps" is dirty
		audit step period is not within audit period

	then
		set "steps" invalid
		set period error messages for "steps"

end

rule "show invisible audittype_text [I, V]"

    salience 180
    no-loop true

    when
        "audittype_text" is filled

    then
        set "audittype_text" visible

end

rule "show invisible notconformreason [I, V]"

    salience 170
    no-loop true

    when
        "notconformreason" is filled

    then
        set "notconformreason" visible

end

# ---- not needed because the for renderer prevents forbidden owner status changes ----
#rule "prevent forbidden owner status change [V]"
#
#    salience 160
#    no-loop true
#
#    when
#        value comparison fulfilled: ":persistent:" attr_value "owner_status" "CONTAINS" value "in_preparation"
#        value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS NOT" value "in_preparation"
#        value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS NOT" value "released"
#
#    then
#        set "owner_status" invalid
#		add "error" message "error.audit.owner.status.change.forbidden.ERR" to "owner_status"
#
#end

rule "define controlstartdate and controlenddate mandatory [I,V]"

    salience 150
    no-loop true

    when
    	"scope" is filled

    then
        set "controlstartdate" mandatory
        set "controlenddate" mandatory

end

rule "auditstarte before plannedstartdate [V]"

	salience 140
	no-loop true

	when
		"auditstartdate" is filled
		"plannedstartdate" is filled
		attribute comparison fulfilled: ":transient:" attr_value "plannedstartdate" "GREATER THAN" ":transient:" attr_value "auditstartdate"

	then
		set "auditstartdate" invalid
		add "error" message "error.audit.auditstartdate.ERR" to "auditstartdate"

end

rule "auditstartdate_invalid_[V]"

	salience 130
	no-loop true

	when
		"auditstartdate" is filled
		"auditenddate" is filled
		attribute comparison fulfilled: ":transient:" attr_value "auditstartdate" "GREATER THAN" ":transient:" attr_value "auditenddate"

	then
		set "auditstartdate" invalid
		add "error" message "error.date.range.DBI" to "auditstartdate"

end

rule "controlperiod_invalid_[V]"

	salience 120
	no-loop true

	when
		"controlstartdate" is filled
		"controlenddate" is filled
		attribute comparison fulfilled: ":transient:" attr_value "controlstartdate" "GREATER THAN" ":transient:" attr_value "controlenddate"

	then
		set "controlstartdate" invalid
		add "error" message "error.date.range.DBI" to "controlstartdate"

end

rule "controlstartdate_invalid_[V]"

	salience 10200
	no-loop true

	when
		"auditstartdate" is filled
		"controlstartdate" is filled
		attribute comparison fulfilled: ":transient:" attr_value "controlstartdate" "GREATER THAN" ":transient:" attr_value "auditstartdate"

	then
		set "controlstartdate" invalid
		add "error" message "error.audit.controlstartdate.ERR" to "controlstartdate"

end

rule "controlenddate_invalid_[V]"

	salience 10200
	no-loop true

	when
		"auditenddate" is filled
		"controlenddate" is filled
		attribute comparison fulfilled: ":transient:" attr_value "controlenddate" "GREATER THAN" ":transient:" attr_value "auditenddate"

	then
		set "controlenddate" invalid
		add "error" message "error.audit.controlenddate.ERR" to "controlenddate"

end

rule "changed_auditstartdate_invalid_[V]"

	salience 110
	no-loop true

	when
		"auditstartdate" is filled
		"auditstartdate" is dirty
		"auditenddate" is filled
		"steps" is filled
		attribute comparison fulfilled: ":transient:" attr_value "auditstartdate" "GREATER THAN" ":persistent:" attr_value "auditstartdate"
		"auditstartdate" after first auditstepstartdate

	then
		set "auditstartdate" invalid
		set period error messages for "auditstartdate"

end

rule "changed_auditenddate_invalid_[V]"

	salience 100
	no-loop true

	when
		"auditstartdate" is filled
		"auditenddate" is filled
		"auditenddate" is dirty
		"steps" is filled
		attribute comparison fulfilled: ":transient:" attr_value "auditenddate" "LESS THAN" ":persistent:" attr_value "auditenddate"
		"auditenddate" before latest auditstependdate

	then
		set "auditenddate" invalid
		set period error messages for "auditenddate"

end
