package ISSUE_RuleSet
expander custom_issue.dsl
#expander issue.dsl

import com.idsscheer.webapps.arcm.bl.re.ext.CollectiveHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelper;
import com.idsscheer.webapps.arcm.bl.component.issuemanagement.re.IssueHelperCustom;

# OBJECT        client_objid         LONG       Client ID                                                                                                                                                   
# OBJECT        client_sign          CLIENTSIGN Client                                                                                                                                                      
# OBJECT        create_date          DATE       Creation date                                                                                                                                               
# OBJECT        creator_user_id      LONG       User ID (creator)                                                                                                                                           
# OBJECT        delete_date          DATE       Deletion date                                                                                                                                               
# OBJECT        guid                 STRING     GUID                                                                                                                                                        
# OBJECT        obj_id               LONG       ID                                                                                                                                                          
# OBJECT        obj_type             OBJECTTYPE Object type                                                                                                                                                 
# OBJECT        root_guid            STRING     Root GUID                                                                                                                                                   
# OBJECT        versions             LONG       Number of versions                                                                                                                                          
# VERSION       aris_change_date     DATE       ARIS change date                                                                                                                                            
# VERSION       change_date          DATE       Change date                                                                                                                                                 
# VERSION       change_type          ENUM       Change type                changetype (created=0,unchanged=1,changed=2,deleted=3,xmlcreated=4,xmlchanged=5,xmldeleted=6)                                    
# VERSION       change_user_id       LONG       User ID (editor)                                                                                                                                            
# VERSION       deactivated          BOOLEAN    Deactivated                                                                                                                                                 
# VERSION       id                   LONG       ID                                                                                                                                                          
# VERSION       substitute_user_id   LONG       User ID (substitute)                                                                                                                                        
# VERSION       version_active       BOOLEAN    Current version                                                                                                                                             
# VERSION       version_number       LONG       Version number                                                                                                                                              
# TRANSACTIONAL execution_date       DATE       Processed on                                                                                                                                                
# TRANSACTIONAL owner                LIST       Performed by               to 1 USER (LT=3105)                                                                                                              
# TRANSACTIONAL owner_group          LIST       Owner group                to 0 USERGROUPs (LT=4019)                                                                                                        
# TRANSACTIONAL owner_status         ENUM       Owner status               issue_owner_status (all=-1,open=0,to_be_reviewed=-2,new=1,in_progress=2,finished=3,on_hold=4,not_possible=5,open_for_execution=6)
# TRANSACTIONAL owner_substitute     LIST       Performed by (substitute)  to 1 USER (LT=3106)                                                                                                              
# TRANSACTIONAL review_date          DATE       Review date                                                                                                                                                 
# TRANSACTIONAL reviewer             LIST       Reviewer                   to 1 USER (LT=4022)                                                                                                              
# TRANSACTIONAL reviewer_group       LIST       Reviewer group             to 0 USERGROUPs (LT=4021)                                                                                                        
# TRANSACTIONAL reviewer_status      ENUM       Reviewer status            issue_reviewer_status (all=-1,to_be_approved=1,approved=2,not_approved=3)                                                        
# TRANSACTIONAL reviewer_substitute  LIST       Reviewer (substitute)      to * USERs (LT=4023)                                                                                                             
# MONITORABLE   controlenddate       DATE       End of control period                                                                                                                                       
# MONITORABLE   controlstartdate     DATE       Start of control period                                                                                                                                     
# MONITORABLE   plannedenddate       DATE       Remediation planned before                                                                                                                                  
# MONITORABLE   plannedstartdate     DATE       Start date                                                                                                                                                  
# ISSUE         category             ENUM       Issue category             issue_category (all=-1,please_select=0,finance=1,compliance=2,operations=3)                                                      
# ISSUE         created_by_testcase  BOOLEAN    Generated by test case                                                                                                                                      
# ISSUE         creator              LIST       Issue creator              to 1 USER (LT=3103)                                                                                                              
# ISSUE         creator_status       ENUM       Creator status             issue_creator_status (all=-1,open=0,new=1,in_creation=2,released=3)                                                              
# ISSUE         description          TEXT       Description                                                                                                                                                 
# ISSUE         documents            LIST       Documents                  to * DOCUMENTs (LT=3104)                                                                                                         
# ISSUE         immediateMeasure     TEXT       Immediate measure                                                                                                                                           
# ISSUE         issueRelevantObjects LIST       Issue-relevant objects     to * OBJECTs (LT=3102)                                                                                                           
# ISSUE         name                 STRING     Name                                                                                                                                                        
# ISSUE         owner_remark         TEXT       Remark (issue owner)                                                                                                                                        
# ISSUE         owners               LIST       Issue owner                to * USERs (LT=3100)                                                                                                             
# ISSUE         priority             ENUM       Priority                   issuePriority (all=-1,low=1,medium=2,high=3)                                                                                     
# ISSUE         relatedTestcaseID    LONG       ID (related test case)                                                                                                                                      
# ISSUE         remark               TEXT       Remark                                                                                                                                                      
# ISSUE         remediationMeasure   TEXT       Remediation measure                                                                                                                                         
# ISSUE         reviewer_remark      TEXT       Remark (issue reviewer)                                                                                                                                     
# ISSUE         reviewers            LIST       Issue reviewer             to * USERs (LT=3101)                                                                                                             
# ISSUE         stateTime            ENUM       Due status                 issueStateTime (all=-1,on_time=1,overdue=2)                                                                                      

# DO NOT CHANGE THE LINES ABOVE - all of them will be updated automatically by tool com.idsscheer.webapps.arcm.bl.re.RETemplater

################################################
### All workflow states - before state rules ###

#################################
### Workflow state "PREPARED" ###

rule "event import job - opened by creator --> init attribute states [I,V]"

	salience 3300
	no-loop true

	when
		( is in workflow state "PREPARED" AND
          user is executing job with id "eventImportJob" )

	then
		set "name"                    editable
		set "description"             editable
		set "remediationMeasure"      editable

		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
end

rule "event import job - creator state set to 'released' --> set workflow fields mandatory for creator [I,V]"

	salience 3200
	no-loop true

	when
		( is in workflow state "PREPARED" AND
          user is executing job with id "eventImportJob" )
		value comparison fulfilled: ":transient:" attr_value "creator_status" "CONTAINS" value "released"

	then
		set "plannedenddate"           editable
		set "owners"                   editable
		set "reviewers"                editable

	    set "plannedenddate"           mandatory
		set "owners"                   mandatory
		set "reviewers"                mandatory

end

########################################
### Workflow state "openForCreation" ###

rule "custom_GRC66 opened by creator --> init attribute states [I,V]"

	salience 2101
	no-loop true

	when
		( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		# during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "please_select"

	then
		set "name"                    editable
		set "description"             editable
		set "creator_status"          invisible #GAP - GRC66
		set "remark"                  editable
		set "issueRelevantObjects"    editable
		set "priority"                editable
		set "category"                editable
		set "immediateMeasure"        editable
		set "remediationMeasure"      editable
		set "plannedenddate"          editable
		set "owners"                  editable
		set "reviewers"               editable
		set "documents"               editable
		set "action_type"             editable #GAP - GRC66
		set "process_environment"	  editable #GAP - GRC74
		set "acting_front"            editable #GAP - GRC74
		set "root_cause"              editable #GAP - GRC74
		set "business_unit"           editable #GAP - GRC74
		set "issuesource"             editable
		
		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
		set "acting_front"            mandatory #GAP - GRC74
		set "plannedenddate"		  mandatory
		
#		set "replanned"               editable  #GAP - GRC74
#		set "recurrent"	              editable  #GAP - GRC74
		set "replanned"               readonly
		set "recurrent"	              readonly

		set "owner_status"            invisible
		set "owner_remark"            invisible
		set "reviewer_status"         invisible
		set "reviewer_remark"         invisible
		set "stateTime"               invisible
		
		set "custom_is_creator_status"   invisible #GAP - GRC66
		set "custom_is_owner_status"     invisible #GAP - GRC66
		set "custom_is_reviewer_status"  invisible #GAP - GRC66
		set "custom_ap_creator_status"   invisible #GAP - GRC66
		set "custom_ap_owner_status"     invisible #GAP - GRC66
		set "custom_ap_reviewer_status"  invisible #GAP - GRC66

end

rule "custom_GRC66_is opened by creator --> init attribute states [I,V]"

	salience 2100
	no-loop true

	when
		( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		# during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"

	then
		set "name"                    editable
		set "description"             editable
		set "creator_status"          invisible #GAP - GRC66
		set "remark"                  editable
		set "issueRelevantObjects"    editable
		set "priority"                editable
		set "category"                editable
		set "immediateMeasure"        editable
		set "remediationMeasure"      editable
		set "plannedenddate"          editable
		set "owners"                  editable
		set "reviewers"               editable
		set "documents"               editable
		set "action_type"             editable #GAP - GRC66
		set "process_environment"	  editable #GAP - GRC74
		set "acting_front"            editable #GAP - GRC74
		set "root_cause"              editable #GAP - GRC74
		set "business_unit"           editable #GAP - GRC74
		set "issuesource"             editable
		
#		set "replanned"               editable  #GAP - GRC74
#		set "recurrent"	              editable  #GAP - GRC74
		set "replanned"               readonly
		set "recurrent"	              readonly
				
		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
		set "acting_front"            mandatory #GAP - GRC74
		set "plannedenddate"		  mandatory
		
		set "owner_status"            invisible
		set "owner_remark"            invisible
		set "reviewer_status"         invisible
		set "reviewer_remark"         invisible
		set "stateTime"               invisible
		
		set "custom_is_creator_status"   editable  #GAP - GRC66
		set "custom_is_owner_status"     invisible #GAP - GRC66
		set "custom_is_reviewer_status"  invisible #GAP - GRC66
		set "custom_ap_creator_status"   invisible #GAP - GRC66
		set "custom_ap_owner_status"     invisible #GAP - GRC66
		set "custom_ap_reviewer_status"  invisible #GAP - GRC66

end

rule "custom_GRC66_ap opened by creator --> init attribute states [I,V]"

	salience 2099
	no-loop true

	when
		( is in workflow state "PREPARED" OR
		  is in workflow state "apOpenForCreation" )
		# during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"

	then
		set "name"                    editable
		set "description"             editable
		set "creator_status"          invisible #GAP - GRC66
		set "remark"                  editable
		set "issueRelevantObjects"    editable
		set "priority"                editable
		set "category"                editable
		set "immediateMeasure"        editable
		set "remediationMeasure"      editable
		set "plannedenddate"          editable
		set "owners"                  editable
		set "reviewers"               editable
		set "documents"               editable
		set "action_type"             editable #GAP - GRC66
		set "process_environment"	  editable #GAP - GRC74
		set "acting_front"            editable #GAP - GRC74
		set "root_cause"              editable #GAP - GRC74
		set "business_unit"           editable #GAP - GRC74
		set "issuesource"             editable

#		set "replanned"               editable  #GAP - GRC74
		set "replanned"               readonly
		set "recurrent"	              readonly  #GAP - GRC74

		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
		set "acting_front"            mandatory #GAP - GRC74
		set "plannedenddate"		  mandatory

		set "owner_status"            invisible
		set "owner_remark"            invisible
		set "reviewer_status"         invisible
		set "reviewer_remark"         invisible
		set "stateTime"               invisible
		
		set "custom_is_creator_status"   invisible #GAP - GRC66
		set "custom_is_owner_status"     invisible #GAP - GRC66
		set "custom_is_reviewer_status"  invisible #GAP - GRC66
		set "custom_ap_creator_status"   editable  #GAP - GRC66
		set "custom_ap_owner_status"     invisible #GAP - GRC66
		set "custom_ap_reviewer_status"  invisible #GAP - GRC66

end

rule "custom_GRC66_ap_hold opened by creator --> init attribute states [I,V]"

	salience 2098
	no-loop true

	when
		( is in workflow state "PREPARED" OR
		  is in workflow state "apCreatorOnHold" )
		# during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"

	then
		set "name"                    editable
		set "description"             editable
		set "creator_status"          invisible #GAP - GRC66
		set "remark"                  editable
		set "issueRelevantObjects"    editable
		set "priority"                editable
		set "category"                editable
		set "immediateMeasure"        editable
		set "remediationMeasure"      editable
		set "plannedenddate"          editable
		set "owners"                  editable
		set "reviewers"               editable
		set "documents"               editable
		set "action_type"             editable #GAP - GRC66
		set "process_environment"	  editable #GAP - GRC74
		set "acting_front"            editable #GAP - GRC74
		set "root_cause"              editable #GAP - GRC74
		set "business_unit"           editable #GAP - GRC74
		
#		set "replanned"               editable  #GAP - GRC74
		set "replanned"               readonly
		set "recurrent"	              readonly  #GAP - GRC74
		
		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
		set "acting_front"            mandatory #GAP - GRC74
		set "plannedenddate"		  mandatory

		set "owner_status"            invisible
		set "owner_remark"            invisible
		set "reviewer_status"         invisible
		set "reviewer_remark"         invisible
		set "stateTime"               invisible
		
		set "custom_is_creator_status"   invisible #GAP - GRC66
		set "custom_is_owner_status"     invisible #GAP - GRC66
		set "custom_is_reviewer_status"  invisible #GAP - GRC66
		set "custom_ap_creator_status"   editable  #GAP - GRC66
		set "custom_ap_owner_status"     invisible #GAP - GRC66
		set "custom_ap_reviewer_status"  invisible #GAP - GRC66

end

# rule engine needs to be executed when the attribute value of "owner" is changed.
rule "custom_GRC66_is creator state set to 'released' --> set workflow fields mandatory for creator [I,V]"

	salience 2000
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "custom_is_creator_status" "CONTAINS" value "in_review"
#		value comparison fulfilled: ":transient:" attr_value "creator_status" "CONTAINS" value "released"

	then
		set "plannedenddate"           mandatory
		set "owners"                   mandatory
		set "reviewers"                mandatory

end

rule "custom_GRC66_ap creator state set to 'released' --> set workflow fields mandatory for creator [I,V]"

	salience 1999
	no-loop true

	when
	    ( is in workflow state "PREPARED" OR
		  is in workflow state "apOpenForCreation" )
	    # during creation the issue manager has the same rights as the creator
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
	    value comparison fulfilled: ":transient:" attr_value "custom_ap_creator_status" "CONTAINS" value "in_review"
#		value comparison fulfilled: ":transient:" attr_value "creator_status" "CONTAINS" value "released"

	then
		set "plannedenddate"           mandatory
		set "owners"                   mandatory
		set "reviewers"                mandatory

end

###########################################################
# Customized Rules - GAP GRC66                    #########
###########################################################
#rule "custom_GRC66_set_issue_status[I,V]"
#
#	salience 1900
#	no-loop true
#	
#	when
#	    ( is in workflow state "PREPARED" OR
#		  is in workflow state "openForCreation" )
#	    # during creation the issue manager has the same rights as the creator
#		( object is opened by its creator OR
#		  user has at object role "issuemanager" )
#		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
#		
#	then
#		set "custom_is_owner_status"      invisible
#		set "custom_is_reviewer_status"   invisible
#		set "custom_ap_creator_status"    invisible
#		set "custom_ap_owner_status"      invisible
#		set "custom_ap_reviewer_status"   invisible  
#
#end

#rule "custom_GRC66_set_actionplan_status[I,V]"
#
#	salience 1800
#	no-loop true
#	
#	when
#	    ( is in workflow state "PREPARED" OR
#		  is in workflow state "openForCreation" )
#	    # during creation the issue manager has the same rights as the creator
#		( object is opened by its creator OR
#		  user has at object role "issuemanager" )
#		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
#		
#	then
#		set "custom_is_creator_status"    invisible
#		set "custom_is_owner_status"      invisible
#		set "custom_is_reviewer_status"   invisible
#		set "custom_ap_owner_status"      invisible
#		set "custom_ap_reviewer_status"   invisible  
#
#end

##########################################
### Workflow state "openForExecution"  ###

#issue manager rules
rule "custom_GRC66_is opened by manager & issue in owner_state 'new' --> init [I,V]"

    salience 1300
	no-loop true

	when
		is in workflow state "openForExecution"
		user has at object role "issuemanager"
		value comparison fulfilled: ":transient:" attr_value "custom_is_owner_status" "CONTAINS" value "in_review"
#		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "new"

	then
		set "name"                    editable
		set "description"             editable
		set "remark"                  editable
		set "issueRelevantObjects"    editable
		set "priority"                editable
		set "category"                editable
		set "immediateMeasure"        editable
		set "remediationMeasure"      editable
#		set "plannedenddate"          editable
		set "plannedenddate"          readonly
		set "owners"                  editable
		set "reviewers"               editable
		set "documents"               editable
		
#		set "replanned"               editable  #GAP - GRC74
#		set "recurrent"	              editable  #GAP - GRC74
		set "replanned"               readonly
		set "recurrent"	              readonly
		
		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
#        set "plannedenddate"          mandatory
		set "owners"                  mandatory
		set "reviewers"               mandatory
		

end

rule "custom_GRC66_ap opened by manager & issue in owner_state 'new' --> init [I,V]"

    salience 1299
	no-loop true

	when
		is in workflow state "apOpenForExecution"
		user has at object role "issuemanager"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_owner_status" "CONTAINS" value "in_review"
#		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "new"

	then
		set "name"                    editable
		set "description"             editable
		set "remark"                  editable
		set "issueRelevantObjects"    editable
		set "priority"                editable
		set "category"                editable
		set "immediateMeasure"        editable
		set "remediationMeasure"      editable
		set "plannedenddate"          editable
		set "owners"                  editable
		set "reviewers"               editable
		set "documents"               editable

#		set "replanned"               editable  #GAP - GRC74
#		set "recurrent"	              editable  #GAP - GRC74
		set "replanned"               readonly
		set "recurrent"	              readonly
		
		set "name"                    mandatory
		set "description"             mandatory
		set "remediationMeasure"      mandatory
        set "plannedenddate"          mandatory
		set "owners"                  mandatory
		set "reviewers"               mandatory

end

rule "custom_GRC66_is opened by manager & issue in owner_state 'in_progress' or 'on_hold' --> init [I,V]"

    salience 1200
	no-loop true

	when		
		( ( is in workflow state "openForExecution" AND
			value comparison fulfilled: ":transient:" attr_value "custom_is_owner_status" "CONTAINS" value "in_progress" ) OR
#		    value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "in_progress" ) OR
		  is in workflow state "onHold" ) AND
		user has at object role "issuemanager"

	then
#		set "plannedenddate"          editable
		set "plannedenddate"          readonly
		set "owners"                  editable
		set "reviewers"               editable

#        set "plannedenddate"          mandatory
		set "owners"                  mandatory
		set "reviewers"               mandatory			

end

rule "custom_GRC66_ap opened by manager & issue in owner_state 'in_progress' or 'on_hold' --> init [I,V]"

    salience 1199
	no-loop true

	when		
		( ( is in workflow state "apOpenForExecution" AND
		    value comparison fulfilled: ":transient:" attr_value "custom_ap_owner_status" "CONTAINS" value "in_progress" ) OR
#		    value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "in_progress" ) OR
		  is in workflow state "apOnHold" ) AND
		user has at object role "issuemanager"

	then
		set "plannedenddate"          editable
		set "owners"                  editable
		set "reviewers"               editable

        set "plannedenddate"          mandatory
		set "owners"                  mandatory
		set "reviewers"               mandatory

end

#issue owner rules
rule "opened by owner & still open for owner --> init [I,V]"

	salience 1100
	no-loop false

	when
		( is in workflow state "openForExecution" OR
		  is in workflow state "onHold" )
		user is assigned in list "owners"

	then
#		set "owner_status"  editable
		set "owner_remark"  editable
		set "documents"     editable
		set "issuesource"   readonly
		
#		set "owner_status"  mandatory

end

rule "ap opened by owner & still open for owner --> init [I,V]"

	salience 1099
	no-loop false

	when
		( is in workflow state "apOpenForExecution" OR
		  is in workflow state "apOnHold" )
		user is assigned in list "owners"

	then
#		set "owner_status"  editable
		set "owner_remark"  editable
		set "documents"     editable
		set "issuesource"   readonly
		
#		set "owner_status"  mandatory

end

#custom issue owner rules - GRC66
rule "custom_grc66_is opened by owner & still open for owner --> init [I,V]"

	salience 1090
	no-loop false

	when
		( is in workflow state "openForExecution" OR
		  is in workflow state "onHold" )
		user is assigned in list "owners"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"

	then
		set "custom_is_owner_status"  editable
		set "custom_is_owner_status"  mandatory
		
		set "creator_status"             invisible
		set "owner_status"               invisible
		set "reviewer_status"            invisible
		set "custom_is_creator_status"   invisible
		set "custom_ap_owner_status"     invisible
		set "custom_is_reviewer_status"  invisible
		set "custom_ap_reviewer_status"  invisible
#		set "recurrent"	                 editable  #GAP - GRC74
		set "recurrent"	                 readonly

end

rule "custom_grc66_ap opened by owner & still open for owner --> init [I,V]"

	salience 1080
	no-loop false

	when
		( is in workflow state "apOpenForExecution" OR
		  is in workflow state "apOnHold" )
		user is assigned in list "owners"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"

	then
		set "custom_ap_owner_status"  editable
		set "custom_ap_owner_status"  mandatory
		
		set "creator_status"             invisible
		set "owner_status"               invisible
		set "reviewer_status"            invisible
		set "custom_is_creator_status"   invisible
		set "custom_is_owner_status"     invisible
		set "custom_is_reviewer_status"  invisible
		set "custom_ap_reviewer_status"  invisible		

end

rule "custom_GRC66_is_in_progress [I,V]"

    salience 1070
	no-loop true

	when
		( is in workflow state "openForExecution" OR
		  is in workflow state "onHold" )
		user is assigned in list "owners"
		value comparison fulfilled: ":transient:" attr_value "custom_is_owner_status" "CONTAINS" value "in_progress"

	then
#		set "plannedenddate"          editable
#		set "owners"                  editable
#		set "reviewers"               editable
#       set "plannedenddate"          mandatory
#		set "owners"                  mandatory
#		set "reviewers"               mandatory

end

rule "custom_GRC66_ap_in_progress [I,V]"

    salience 1060
	no-loop true

	when
		( is in workflow state "apOpenForExecution" OR
		  is in workflow state "onHold" )
		user is assigned in list "owners"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_owner_status" "CONTAINS" value "in_progress"

	then
#		set "plannedenddate"          editable
#		set "owners"                  editable
#		set "reviewers"               editable
#		set "replanned"               editable  #GAP - GRC74 2304
		set "replanned"               readonly

#       set "plannedenddate"          mandatory
#		set "owners"                  mandatory
#		set "reviewers"               mandatory

end

# rule engine needs to be executed when the attribute value of "ownerStatus" is changed.
rule "ownerStatus just set to 'not possible'--> set fields mandatory [I,V]"

	salience 1000
	no-loop true

	when
	    ( is in workflow state "openForExecution" OR
		  is in workflow state "onHold" )
		user is assigned in list "owners"
		value comparison fulfilled: ":transient:" attr_value "owner_status" "CONTAINS" value "not_possible"

	then
		set "owner_remark" mandatory

end

#######################################
### Workflow state "openForReview"  ###

rule "custom_GRC66_is opened by reviewer, still editable --> init [I,V]"

	salience 1300
	no-loop true

	when
		is in workflow state "openForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"

	then
		set "custom_is_reviewer_status" editable
		set "custom_is_reviewer_status" mandatory
#		set "reviewers"                 mandatory
	
#		set "reviewer_status" editable
		set "reviewer_remark" editable
		set "documents"       editable
#		set "recurrent"	      editable  #GAP - GRC74
		set "recurrent"	      readonly
		
#		set "reviewer_status" mandatory

		set "creator_status"             invisible
		set "owner_status"               invisible
		set "reviewer_status"            invisible
#		set "custom_ap_creator_status"   invisible
#		set "custom_ap_owner_status"     invisible
#		set "custom_ap_reviewer_status"  invisible

end

rule "custom_GRC66_ap opened by reviewer, still editable --> init [I,V]"

	salience 1290
	no-loop true

	when
		( ( is in workflow state "apOpenForReview" ) OR
		  ( is in workflow state "apDirectReview" ) )
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"

	then
		set "custom_ap_reviewer_status" editable
		set "custom_ap_reviewer_status" mandatory
	
#		set "reviewer_status" editable
		set "reviewer_remark" editable
		set "documents"       editable	
#		set "plannedenddate"  editable
#		set "replanned"       editable  #GAP - GRC74 2304
		set "replanned"       readonly
		
#		set "reviewer_status" mandatory

		set "creator_status"             invisible
		set "owner_status"               invisible
		set "reviewer_status"            invisible
		set "custom_is_creator_status"   invisible
		set "custom_is_owner_status"     invisible
		set "custom_is_reviewer_status"  invisible

end

rule "custom_GRC66_is opened by reviewer, remediation planned before editable [I,V]"

	salience 1200
	no-loop true

	when
	    is in workflow state "openForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
		value comparison fulfilled: ":transient:" attr_value "custom_is_reviewer_status" "CONTAINS" value "fup"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "not_approved"

	then
#		set "plannedenddate" editable

end

rule "custom_GRC66_ap opened by reviewer, remediation planned before editable [I,V]"

	salience 1190
	no-loop true

	when
	    is in workflow state "apOpenForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_reviewer_status" "CONTAINS" value "fup"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "not_approved"

	then
#		set "plannedenddate" editable

end

rule "custom_GRC66_ap2 opened by reviewer, remediation planned before editable [I,V]"

	salience 1180
	no-loop true

	when
	    is in workflow state "apOpenForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_reviewer_status" "CONTAINS" value "risk_assumed"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "not_approved"

	then
#		set "plannedenddate" editable

end

rule "custom_GRC66_is opened by reviewer and not disagreed => plannedenddate + stateTime restored to persistent value, plannedenddate readonly [I,V]"

	salience 1100
	no-loop true

	when
	    is in workflow state "openForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
		value comparison fulfilled: ":transient:" attr_value "custom_is_reviewer_status" "CONTAINS NOT" value "fup"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS NOT" value "not_approved"

	then
#		set "plannedenddate" editable

end

rule "custom_GRC66_ap opened by reviewer and not disagreed => plannedenddate + stateTime restored to persistent value, plannedenddate readonly [I,V]"

	salience 1090
	no-loop true

	when
	    is in workflow state "apOpenForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_reviewer_status" "CONTAINS NOT" value "fup"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS NOT" value "not_approved"

	then
#		set "plannedenddate" editable

end

rule "custom_GRC66_ap2 opened by reviewer and not disagreed => plannedenddate + stateTime restored to persistent value, plannedenddate readonly [I,V]"

	salience 1090
	no-loop true

	when
	    is in workflow state "apOpenForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_reviewer_status" "CONTAINS NOT" value "risk_assumed"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS NOT" value "not_approved"

	then
#		set "plannedenddate" editable

end

rule "custom_GRC66_is reviewer has to decide to a legal issue reviewer state [V]"

	salience 1000
	no-loop true

	when
		is in workflow state "openForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
		value comparison fulfilled: ":transient:" attr_value "custom_is_reviewer_status" "CONTAINS" value "in_progress"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "to_be_approved"
		object is dirty

	then
#		set "reviewer_status" invalid
#		add "error" message "error.issue.reviewer.state.not.allowed.ERR" to "reviewer_status"

end

rule "custom_GRC66_ap reviewer has to decide to a legal issue reviewer state [V]"

	salience 900
	no-loop true

	when
		is in workflow state "apOpenForReview"
		user is assigned in list "reviewers"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_reviewer_status" "CONTAINS" value "in_progress"
#		value comparison fulfilled: ":transient:" attr_value "reviewer_status" "CONTAINS" value "to_be_approved"
		object is dirty

	then
#		set "reviewer_status" invalid
#		add "error" message "error.issue.reviewer.state.not.allowed.ERR" to "reviewer_status"

end

###############################################
### All workflow states - after state rules ###

rule "hide field created by test case [I,V]"

	salience 130
	no-loop true

	when
		value comparison fulfilled: ":persistent:" attr_value "created_by_testcase" "EQUALS NOT" value "true"

	then
		set "created_by_testcase" invisible

end

rule "remediation does not be a thing of the past [V]"

	salience 120
	no-loop true

	when
		"plannedenddate" is dirty
		"plannedenddate" is filled
		value comparison fulfilled: ":transient:" attr_value "plannedenddate" "LESS THAN" value ":TODAY:"

	then
		set "plannedenddate" invalid
		add "error" message "issue.remediation.planned.before.not.before.today.ERR" to "plannedenddate"

end

rule "'remediation planned before' is filled --> check overdue state [V]"

	salience 110
	no-loop true

	when
		"plannedenddate" is filled

	then
		recalculate time dependent state

end

rule "custom_issue_earlier_than_first_version[I,V]"

	salience 105
	no-loop true
	
	when
		is issue earlier than first version
		
	then
#		add "error" message "issue.remediation.planned.before.not.before.today.ERR" to "plannedenddate"
#		adding "error" message "issue.error.plannedenddate.late.ERR" to "plannedenddate"	
#		add object "ERROR" message "custom.error.issue.plannedenddate.late.DBI"
#		add object "error" message "issue.error.plannedenddate.late.ERR"

end


###########################################################
# Customized Rules - GAP GRC66                    #########
###########################################################
rule "custom_is_set_creator_status[I,V]"

	salience 100
	no-loop true

	when
		is in workflow state "closedByReviewer"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
		
	then
		set "custom_is_creator_status"   readonly
		set "custom_is_owner_status"     readonly
		set "custom_is_reviewer_status"  readonly
		set "issuesource"                readonly
		
		set "creator_status"             invisible
		set "owner_status"               invisible
		set "reviewer_status"            invisible
		
		set "custom_ap_creator_status"   invisible
		set "custom_ap_owner_status"     invisible
		set "custom_ap_reviewer_status"  invisible  

		
end

rule "custom_ap_set_creator_status[I,V]"

	salience 100
	no-loop true

	when
		is in workflow state "apClosedByReviewer"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
		
	then
		set "custom_ap_creator_status"   readonly
		set "custom_ap_owner_status"     readonly
		set "custom_ap_reviewer_status"  readonly
		set "issuesource"                readonly
		
		set "creator_status"             invisible
		set "owner_status"               invisible
		set "reviewer_status"            invisible
		
		set "custom_is_creator_status"   invisible
		set "custom_is_owner_status"     invisible
		set "custom_is_reviewer_status"  invisible   
		
end


rule "custom_set_issuesource[I,V]"

	salience 90
	no-loop true

	when

	then
	  	
#		set "issuesource"       editable
		set "priority"          invisible
		set "category"          invisible
end

rule "custom_set_riskclassification[I,V]"

	salience 85
	no-loop true
	
	when
		( value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue" ) OR
		( value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan" )
	
	then
		set risk classification

end

# Inicio REO 07.08.2017 - Evento EV107085
#rule "custom_set_plannedenddate_status_issue[I,V]"
#
#	salience 80
#	no-loop true
#	
#	when
#		( is in workflow state "PREPARED" OR
#		  is in workflow state "openForCreation" )
#		( object is opened by its creator OR
#		  user has at object role "issuemanager" )
#		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
#	
#	then
#		set "plannedenddate" not_mandatory
#		set "plannedenddate" readonly
#		set "custom_is_creator_status" to value "new"
#
#end
#
# Inicio REO 14.08.2017 - Evento EV108435
rule "custom_set_plannedenddate_status_actionplan[I,V]"

	salience 75
	no-loop true
	
	when
		( is in workflow state "PREPARED" OR
		  is in workflow state "apOpenForCreation" )
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
		value comparison fulfilled: ":transient:" attr_value "custom_ap_creator_status" "CONTAINS" value "please_select"
	
	then
#		set "plannedenddate" not_mandatory
#		set "plannedenddate" readonly
		set "custom_ap_creator_status" to value "new"

end
# Fim REO 14.08.2017 - Evento EV108435

# Inicio REO 30.11.2017 - Evento EV121389
rule "custom_set_plannedenddate_status_issue[I,V]"

	salience 70
	no-loop true
	
	when
		( is in workflow state "PREPARED" OR
		  is in workflow state "openForCreation" )
		( object is opened by its creator OR
		  user has at object role "issuemanager" )
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
		value comparison fulfilled: ":transient:" attr_value "custom_is_creator_status" "CONTAINS" value "please_select"
	
	then
#		set "plannedenddate" not_mandatory
#		set "plannedenddate" readonly
		set "custom_is_creator_status" to value "new"

end
# Fim REO 30.11.2017 - Evento EV121389

#rule "custom_set_action_type_mandatory[I,V]"
#	
#	salience 70
#	no-loop true
#	
#	when
#	
#	then
#		set "action_type" mandatory
#		
#end
# Fim REO 07.08.2017 - Evento EV107085

rule "custom_set_change_fields_issue[I,V]"

	salience 65
	no-loop true
	
	when
		user has in_general role "issuemanager"
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"
		
	then
		set "name"        editable
		set "description" editable
#		set "plannedenddate"  editable
#		set "plannedenddate"  readonly
		set "reviewers"   editable
#		set "replanned"   editable
		set "replanned"   readonly
		set "documents"   editable

end

#rule "custom_set_change_fields_actionplan[I,V]"
#
#	salience 64
#	no-loop true
#	
#	when
#		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"
#		
#	then
#		set "name"        editable
#		set "description" editable
#		set "plannedenddate"  editable
#		set "reviewers"   editable
#		set "replanned"   editable
#		set "documents"   editable		
#
#end

################
# DMM - 2018-04-03 - EV167233 -  Impossibilidade de anexar arquivos
################
rule "file_upload_enable[I,V]"

	salience 63
	no-loop true
	
	when
		is in workflow state "openForExecution" OR
		is in workflow state "openForReview"		
	then
		set "documents" editable

end

#DMM - BOF- Revisão da sprint - 14/05/2018

rule "show_hide_action_plan_fields_issue_manager[I,V]"

	salience 62
	no-loop true
	
	when
		is_not in workflow state "apClosedByReviewer"
		(user is systemadmin OR
		user has at object role "issuemanager")
		#(user is_not assigned in list "owners" AND
		#user is_not assigned in list "reviewers")
		#object is_not opened by its creator
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "actionplan"		
	then
	
		#set "custom_ap_creator_status"		invisible	# AP
		#set "custom_ap_owner_status"		invisible	# AP
		#set "custom_ap_reviewer_status"	invisible	# AP


		set "action_type"	 			editable	# AP/I
		set "obj_id"					readonly	# AP/I
		set "name"						editable	# AP/I
		set "issue_date"				readonly	# AP/I
		set "issueRelevantObjects"		readonly	# AP/I
		set "description"				editable	# AP/I
		set "plannedenddate"			editable	# AP/I
		set "replanneddate"				editable	# AP/I
		set "replanned"					editable	# AP/I
		set "recurrent"                 editable
		set "cst_rescheduling" 		 	editable	# AP
		set "recurrent" 	 			editable	# I
		set "stateTime"					readonly	# AP/I
		set "creator"					readonly	# AP/I
		set "owners"					editable	# AP/I
		set "reviewers"					editable	# AP/I
		set "status_obj"				readonly	# AP/I
		set "owner"						readonly	# AP/I
		set "immediateMeasure"			editable	# AP/I
		set "documents"					editable	# AP/I
		set "issuesource"  				editable	# I

end

rule "show_hide_issues_fields_issue_manager[I,V]"

	salience 61
	no-loop true
	
	when
		is_not in workflow state "closedByReviewer"
		(user is systemadmin OR
		user has at object role "issuemanager")
		#(user is_not assigned in list "owners" AND
		#user is_not assigned in list "reviewers" AND
		#object is_not opened by its creator)
		value comparison fulfilled: ":transient:" attr_value "action_type" "CONTAINS" value "issue"		
	then

		#set "custom_is_creator_status"	invisible	# I
		#set "custom_is_owner_status"	invisible	# I
		#set "custom_is_reviewer_status"	invisible	# I


		set "action_type" 				editable	# AP/I
		set "issuesource"  				editable	# I
		set "obj_id"					readonly	# AP/I
		set "name"						editable	# AP/I
		set "issue_date"				readonly	# AP/I
		set "issueRelevantObjects"		readonly	# AP/I
		set "description"				editable	# AP/I
		set "root_cause"  				editable	# I
		set "remediationMeasure"  		editable	# I
#		set "plannedenddate"			editable	# AP/I
#		set "plannedenddate"			readonly	# AP/I
		set "replanneddate"				readonly	# AP/I
		set "fup_date"					readonly	# I
		set "replanned"					editable	# AP/I
		set "stateTime"					readonly	# AP/I
		set "recurrent" 	 			editable	# I
		set "rsk_name"					readonly	# I
		set "ra_result"  				readonly	# I
		set "ra_residualfinal"  		readonly	# I
		set "riskowner"  				readonly	# I
		set "creator"					readonly	# AP/I
		set "owners"					editable	# AP/I
		set "reviewers"					editable	# AP/I
		set "status_obj"				readonly	# AP/I
		set "owner"						readonly	# AP/I
		set "immediateMeasure"			editable	# AP/I
		set "documents"					editable	# AP/I
		set "acting_front"  			editable	# I
		set "process_environment" 		editable	# I
		set "business_unit"				editable	# I
		set "cst_appsystem"  			editable	# I
		set "custom_servicetype"  		editable	# I
		set "auditproject"  			editable	# I
		set "custom_auditauthor"  		editable	# I

end

#DMM - EOF- Revisão da sprint - 14/05/2018